[versions]
jvm = "17"
kotlin = "1.8.21"
junit = "5.9.3"
spring-boot = "3.1.0"
bouncycastle = "1.72"
kotest = "5.5.5"
jacoco = "0.8.10"
restassured = "5.3.0"
qase = "3.0.4"
json-unit = "2.37.0"
medici = "6.0.0"

[libraries]
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }

testng = "org.testng:testng:7.6.1"

lombok = "org.projectlombok:lombok:1.18.26"
assertj = "org.assertj:assertj-core:3.24.2"
kotlin-lib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

spring-boot-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "spring-boot" }
spring-boot-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "spring-boot" }
spring-boot-devtools = { module = "org.springframework.boot:spring-boot-devtools", version.ref = "spring-boot" }

javax-annotation = "javax.annotation:javax.annotation-api:1.3.2"
selenium = "org.seleniumhq.selenium:selenium-java:4.8.1"
webdriver-manager = "io.github.bonigarcia:webdrivermanager:5.3.2"
gcloud-secretmanager = "com.google.cloud:spring-cloud-gcp-starter-secretmanager:4.1.1"
json-jackson-kotlin = "com.fasterxml.jackson.module:jackson-module-kotlin:2.14.2"
bouncycastle-ext = { module = "org.bouncycastle:bcprov-ext-jdk18on", version.ref = "bouncycastle" }
bouncycastle = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bouncycastle" }

restassured-lib = { module = "io.rest-assured:rest-assured", version.ref = "restassured" }
restassured-ext = { module = "io.rest-assured:kotlin-extensions", version.ref = "restassured" }

json-simple = "com.googlecode.json-simple:json-simple:1.1.1"
json-json = "org.json:json:20230227"
json-assert = "net.javacrumbs.json-unit:json-unit-assertj:2.37.0"

json-merge = "com.savvasdalkitsis:json-merge:0.0.6"

json-dsl = "com.github.hitanshu-dhawan:JsonDSL:1.0.3"

medici-auth = { module = "io.medici.tzero:jwt-auth-util", version.ref = "medici" }
medici-model = { module = "io.medici.tzero:jwt-auth-model", version.ref = "medici" }

kotlin-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.0"

kotest-framework-datatest = { module = "io.kotest:kotest-framework-datatest", version.ref = "kotest" }
kotest-framework-api = { module = "io.kotest:kotest-framework-api", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-spring = "io.kotest.extensions:kotest-extensions-spring:1.1.2"

totp = "de.taimos:totp:1.0"

gson = "com.google.code.gson:gson:2.10.1"

qase-api = { module = "io.qase:qase-api", version.ref = "qase" }
qase-junit5 = { module = "io.qase:qase-junit5", version.ref = "qase" }

json-unit = { module = "net.javacrumbs.json-unit:json-unit", version.ref = "json-unit" }
json-unit-assertj = { module = "net.javacrumbs.json-unit:json-unit-assertj", version.ref = "json-unit" }
json-unit-json-path = { module = "net.javacrumbs.json-unit:json-unit-json-path", version.ref = "json-unit" }

[bundles]
junit5 = ["junit-api", "junit-engine", "junit-params"]
selenium = ["selenium", "webdriver-manager"]
spring-boot-test = ["spring-boot-test", "javax-annotation"]
bouncycastle-lib = ["bouncycastle-ext", "bouncycastle"]
kotest = ["kotest-property", "kotest-framework-datatest", "kotest-framework-api", "kotest-runner-junit5", "kotest-spring"]
restassured = ["restassured-lib", "restassured-ext"]
qase = ["qase-api", "qase-junit5"]
json-unit = ["json-unit", "json-unit-assertj", "json-unit-json-path"]
medici = ["medici-auth", "medici-model"]

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency = "io.spring.dependency-management:1.1.0"
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-dsl = "org.gradle.kotlin.kotlin-dsl:4.0.7"
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
ktlint = "org.jlleitschuh.gradle.ktlint:11.0.0"
spotless = "com.diffplug.spotless:6.16.0"
lombok = "io.freefair.lombok:8.0.0-rc2"
